<template>
    <div class="about-section pt-5 pb-3" :class="addClassName">
        <div class="container">
            <div class="row align-items-center">
                <div class="col order-2">
                    <div class="about-content max-w-100 text-center">
                        <h1 class="title d-inline">Política de privacidade</h1>
                        <p class="fz-18 text-justify"><b>CONSIDERANDO que:</b><br/><br/>(I) A Lei nº 13.709/2018, mais conhecida como Lei Geral de Proteção de Dados pessoais (LGPD), passou a regulamentar atividades de Tratamento de Dados Pessoais, inclusive nos meios digitais, por pessoa natural ou por pessoa jurídica de direito público ou privado, com o objetivo de proteger os direitos fundamentais de liberdade e de privacidade e o livre desenvolvimento da personalidade da pessoa natural;<br/><br/>(II) A SUB100 SISTEMAS LTDA, “SUB100”, é a empresa proprietária e responsável pelos sites: https://www.sub100sistemas.com.br/, https://sub100.com.br/, www.sistemasgl.com.br,  https://subseeon.com/, que se destinam a divulgação de seus produtos para fins de comercialização e/ou aproximação de anunciantes e usuários, para facilitar a busca por imóveis para compra, venda e locação e, pelos produtos: Portal de Imóveis SUB100, SUBSEE on, Sistema SGL, Sites & Hotsites e Inteligência imobiliária;<br><br>(III) “Anunciante” são todas as pessoas e empresas que possuem CRECI e se cadastram no site do Portal de Imóveis da SUB100 SISTEMAS LTDA para realizarem o anúncio de imóveis.<br/><br/>A partir das considerações acima e principalmente para atendimento da legislação vigente, a SUB100 através da Política de Privacidade explica:<br/><br/>a) Quais informações coletamos<br/>b) Como usamos essas informações<br/>c) Como compartilharmos<br/>d) Com quem compartilhamos<br/>e) Limitações da responsabilidade quanto a utilização dos dados<br/><br/>Antes de prosseguir com a análise do presente documento, orientamos você, visitante do site, referido como “usuário” a reservar um tempo para conhecer os nossos Termos de Uso.  Ao visitar e utilizar o site, você automaticamente aceita as condições descritas a seguir.</p>
                        <h3 class="title fz-22 pt-4">1.RESTRIÇÃO PARA MENORES</h3><p class="fz-18 text-justify">Os sites da SUB100 foram desenvolvidos para usuários maiores de idade. Recomendamos que crianças e pessoas menores de 18 (dezoito) anos somente utilizem o site acompanhadas dos seus pais ou responsável legal.</p>
                        <h3 class="title fz-22 pt-4">2.FORNECIMENTO DE DADOS</h3><p class="fz-18 text-justify">Tanto para o usuário quanto para os anunciantes, utilizarem de todas as funcionalidades dos sites SUB100 e possibilitar a interação entre a SUB100 e os mesmos, é necessário o fornecimento de dados pessoais. O não fornecimento dos dados implicará no bloqueio/inutilização de algumas funcionalidades.</p>
                        <h3 class="title fz-22 pt-4">3.USUÁRIOS E ANUNCIANTES</h3><h4 class="title fz-22 pt-4">3.1. COLETA DE INFORMAÇÕES</h4><p class="fz-18 text-justify">a) A SUB100 poderá coletar as seguintes informações pessoais, via formulários dos sites: Empresa; CNPJ; Nome; CPF; Email; Telefone; Endereço; Perfil.<br>b) Dados fornecidos pela utilização dos sites SUB100: Dados gerais como IP e sistema operacionais; Dados da localização do usuário/anunciante; Dados de interação entre usuários e entre usuários e anunciantes; Dados sobre como o usuário/anunciante utiliza e interage com os serviços.</p><h4 class="title fz-22 pt-4">3.2. OS DADOS USUÁRIOS</h4><p class="fz-18 text-justify">Os dados coletados acima serão utilizados pela SUB100 para processar e facilitar a interação do usuário nos sites da empresa e também,  para melhorias dos serviços disponibilizados. Os dados permanecerão armazenados em nossos sistemas, sob rígidas práticas de segurança de informação, e conservados em seu cadastro ativo até eventual pedido de exclusão. Também poderão ser utilizados em atendimento a solicitações em processos judiciais e demais órgãos competentes.</p><h4 class="title fz-22 pt-4">3.3. COMPARTILHAMENTO DAS INFORMAÇÕES</h4><p class="fz-18 text-justify">Ao aceitar a presente Política de Privacidade, o usuário e o anunciante concordam de forma expressa com o compartilhamento dos dados com a SUB100, os anunciantes (quando solicitado pelo usuário) e com os usuários (quando exposto pelo anunciante).</p><h4 class="title fz-22 pt-4">3.4. LIMITAÇÃO DE RESPONSABILIDADE</h4><p class="fz-18 text-justify">A SUB100 orienta os anunciantes a utilizarem os dados eventualmente fornecidos pelos usuários e disponibilizados pela SUB100 apenas com os propósitos previstos na Lei Geral de Proteção de Dados, Lei nº 13.709/2018, cabendo aos anunciantes as adequações necessárias.</p>
                        <h3 class="title fz-22 pt-4">4.COOKIES</h3><p class="fz-18 text-justify">Os cookies são tecnologias utilizadas para aprimorar a navegação dos sites da SUB100. Essas tecnologias serão coletadas e armazenadas de forma automática.</p>
                        <h3 class="title fz-22 pt-4">5.SEGURANÇA</h3><p class="fz-18 text-justify">Os Dados fornecidos e tratados pela SUB100 permanecerão armazenados e protegidos por tecnologias e equipamentos de segurança para impedir a divulgação das informações.</p>
                        <h3 class="title fz-22 pt-4">6.DIREITOS DO TITULAR</h3><p class="fz-18 text-justify">Conforme a legislação vigente, o titular pode: confirmar; ter acesso e requisitar a eliminação dos dados, assim como solicitar correções de dados incompletos, inexatos e desatualizados, dentre outras hipóteses previstas no artigo 18 da Lei Geral de Proteção de Dados.</p>
                        <h3 class="title fz-22 pt-4">7.TÉRMINO DO TRATAMENTO</h3><p class="fz-18 text-justify">O tratamento de dados permanecerá pelo tempo necessário ao atendimento do legítimo interesse da SUB100 ou então por solicitação do usuário/anunciante da sua eliminação.</p>
                        <h3 class="title fz-22 pt-4">8.ALTERAÇÃO NA POLÍTICA DE PRIVACIDADE</h3><p class="fz-18 text-justify">Em caso de modificação destes termos, para melhor atender seus clientes (usuários e anunciantes), a SUB100 publicará tais alterações e os notificará sobre esta situação.</p>
                        <h3 class="title fz-22 pt-4">9.CONTATO</h3><p class="fz-18 text-justify">Caso tenha qualquer dúvida em relação à Política de Privacidade, favor entrar em contato: <a href="mailto:privacidade@sub100.com.br">privacidade@sub100.com.br</a>.</p>
                        <h3 class="title fz-22 pt-4">10.FORO</h3><p class="fz-18 text-justify">Fica eleito o Foro Central da Comarca de Maringá - PR, para dirimir quaisquer questões decorrentes desta Política de Privacidade, que será regido pelas leis brasileiras.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        props: ['addClassName'],
        components: {
            ShapeWithAnimation: () => import('@/components/ShapeWithAnimation'),
        },
    }
</script>